EduPlanner 📆 BackEnd application V.1.0.0 🧱
ab-noori/EduPlanner-Backend pull request #24
Opened 2023-10-12 18:01 UTC by gisachris

## IN This PR We present the Edu Planner Appointments Application:🌐 
**This BackEnd Part of the application has undergone its development 👨‍💻 phase and completed successfully**

## Project  KanBan Board
![board](https://github.com/ab-noori/EduPlanner-Backend/assets/125574259/8657d350-6169-4cb9-b925-259b4a6669c4)

## Requirements
- All requirements can be found [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md)

## ACHIEVEMENTS ⛰️
- Application has a fully built and well-designed UI🎨 and UX⚙️ system ready to fulfill all these [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md)
- Link To Application FrontEnd Deployed app [here](https://edu-planner.onrender.com)
- Link To Application BackEnd Deployed app [here](https://edu-planner-backend.onrender.com/)
- Link to Application FrontEnd SourceCode [here](https://github.com/ab-noori/EduPlanner-Frontend)

## NOTE
- In this Project We worked As a Team Of three (@gisachris , @ab-noori , @BANCUNGUYE66 ) and Implemented the Project Requirements to the Best of our Abilities and According to the Project Requirements for a `Groups of three`.

## Conclusion
**We would love to hear 👂  from you Our CR in terms of what can be better implemented 👨‍💻  for the site thank you! And we look forward to hearing from you soon.**  🙇

2023-10-12 18:42 UTC, Meltrust requested changes
_note: the frontend review will be ready in a few minutes._

Hi @gisachris ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-12 18:42 UTC, Meltrust commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] This link to the LICENSE file does not work.  Kindly, link to the correct file to correct it. 👍 

![image](https://github.com/ab-noori/EduPlanner-Backend/assets/57421823/a63268ec-8b2c-4ce5-9d8a-59abe80a2aef)

2023-10-12 18:42 UTC, Meltrust commented on README.md
> +Please feel free to fork this repository for your own projects.
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-10-12 18:42 UTC, Meltrust commented on app/controllers/api/reservations_controller.rb
> +  end
- [ ] What happens is the reservation is not successfully destroyed?  Kindly, add some error handling. 👍

2023-10-12 18:54 UTC, ab-noori commented
**Hi @Meltrust 👋,**
Thank you so much 🙏 for reviewing our pull request.
Your nice feedback is really appreciated 🙏.
Our team will work on the requested changes 🎯

![thank-you-gif-22](https://github.com/ab-noori/bookstore-cms/assets/111179533/0848000e-52ce-440c-a114-6c7f859a0eaa)

2023-10-13 03:40 UTC, gisachris commented
## IN This PR We present the Edu Planner Appointments Application Required Changes(Backend): ♻️
**This application has undergone Making changes ♻️  and has completed Successfully**

## Changes Required
- Implement Error handling on the Backend of the Application.
- Remove `MiniTest` files since we are using `Rspec` for Testing. 🧪 
- Put Proper links to `Licence` file 📜

## ACHIEVEMENTS ⛰️
- All the Above Where achieved. ✅ 

## Conclusion
**We would love to hear 👂  from you Our CR in terms of what can be better implemented 👨‍💻  for the site thank you! And we look forward to hearing from you soon.**  🙇

2023-10-13 10:27 UTC, Meltrust approved these changes
#### Hi @gisachris,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)





Cheers and Happy coding!👏👏👏


------

2023-10-13 10:48 UTC, gisachris commented
@Meltrust  Thank you for the kind review 🤝

2023-10-13 10:48 UTC, merged